# Generated by Django 6.1 on 2026-09-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0021_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
